// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAaSg-9jK13_v189_TWrxVw3PN40me8XLQ',
    appId: '1:806571691541:web:4690e5b3f6fd0ad470481c',
    messagingSenderId: '806571691541',
    projectId: 'fir-getx-app-61061',
    authDomain: 'fir-getx-app-61061.firebaseapp.com',
    storageBucket: 'fir-getx-app-61061.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBXoJafagnw5OuLz7ESc93-4l7BsbIDAaE',
    appId: '1:806571691541:android:395fa7fb0fe8f9f670481c',
    messagingSenderId: '806571691541',
    projectId: 'fir-getx-app-61061',
    storageBucket: 'fir-getx-app-61061.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAZvo-lz2kQb1UHz80GeJJhOLlTcOoiIRU',
    appId: '1:806571691541:ios:700c4c8aad4855e270481c',
    messagingSenderId: '806571691541',
    projectId: 'fir-getx-app-61061',
    storageBucket: 'fir-getx-app-61061.appspot.com',
    iosClientId: '806571691541-cu8eo0lvjja1aehjeud9hk1jnorv2h5i.apps.googleusercontent.com',
    iosBundleId: 'com.example.flutterfireAuth',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAZvo-lz2kQb1UHz80GeJJhOLlTcOoiIRU',
    appId: '1:806571691541:ios:700c4c8aad4855e270481c',
    messagingSenderId: '806571691541',
    projectId: 'fir-getx-app-61061',
    storageBucket: 'fir-getx-app-61061.appspot.com',
    iosClientId: '806571691541-cu8eo0lvjja1aehjeud9hk1jnorv2h5i.apps.googleusercontent.com',
    iosBundleId: 'com.example.flutterfireAuth',
  );
}
